// frontend/src/components/config/RpcExecuteTab.tsx
import { useCallback, useEffect, useMemo, useState } from 'react'
import { Alert, Button, Tag, confirm } from '../../ui'
import { i18n } from '../../i18n'
import { executeRpc, getConfig } from '../../api'
import { extractRows } from '../../utils/extractRows'
import { parseLeafref } from '../../utils/leafref'
import { keyOf } from '../../form/configForm'
import type { Field } from '../../utils/crdSchemaParser'
import type { RpcDef } from '../../utils/moduleConsole'
import FieldRenderer from './FieldRenderer'
import './RpcExecuteTab.scss'

// RpcExecuteTab（FE-19/FE-20）：模型驱动 rpc 执行面板——input 复用 FieldRenderer；
// leafref 输入一律下拉（禁自由文本，目标值经 getConfig+extractRows 拉取，失败=空
// 下拉 R08）；执行前二次确认、高危（ext:execution-warn）升级危险样式；ExecuteRPC
// 有副作用不重试、结果/错误如实回显。语义自旧 Vue 版逐段平移。
const t = (k: string, p?: Record<string, unknown>) => i18n.global.t(k, p)

export interface RpcExecuteTabProps {
  rpc: RpcDef
  module: string
  device: string
}

export default function RpcExecuteTab({ rpc, module, device }: RpcExecuteTabProps) {
  const [values, setValues] = useState<Record<string, any>>({})
  const [leafrefOptions, setLeafrefOptions] = useState<Record<string, { label: string; value: string }[]>>({})
  const [running, setRunning] = useState(false)
  const [result, setResult] = useState('')
  const [resultType, setResultType] = useState<'success' | 'error'>('success')

  // rpc/设备切换：清空输入与结果。
  useEffect(() => {
    setValues({})
    setResult('')
  }, [device, rpc.name])

  // 拉取每个 leafref 输入的目标列表 → 下拉选项（FE-19）。
  useEffect(() => {
    setLeafrefOptions({})
    if (!device) return
    let alive = true
    void (async () => {
      const next: Record<string, { label: string; value: string }[]> = {}
      for (const f of rpc.input) {
        const target = parseLeafref(f.leafRef)
        if (!target) continue
        try {
          const res = await getConfig(device, target.fetchPath)
          const rows = extractRows(res.data?.data, target.listKey, target.keyField)
          const opts = rows
            .map((r) => String(r[target.keyField] ?? ''))
            .filter((v) => v !== '')
            .map((v) => ({ label: v, value: v }))
          if (opts.length) next[keyOf(f)] = opts
        } catch {
          /* 拉取失败=空选项 → 空下拉（R08） */
        }
      }
      if (alive) setLeafrefOptions(next)
    })()
    return () => {
      alive = false
    }
  }, [device, rpc])

  // 渲染用输入字段：leafref 注入 options（FieldRenderer 对 leafRef 恒下拉）。
  const renderFields = useMemo<Field[]>(
    () =>
      rpc.input.map((f) =>
        f.leafRef ? { ...f, options: leafrefOptions[keyOf(f)] ?? [] } : f,
      ),
    [rpc.input, leafrefOptions],
  )

  // 所有 mandatory input 有值才可执行（§9）。
  const submittable = useMemo(
    () =>
      rpc.input.every((f) => {
        if (!f.required) return true
        const v = values[keyOf(f)]
        return v !== undefined && v !== null && String(v).trim() !== ''
      }),
    [rpc.input, values],
  )

  const collectInputs = useCallback((): Record<string, string> => {
    const out: Record<string, string> = {}
    for (const f of rpc.input) {
      const v = values[keyOf(f)]
      if (v !== undefined && v !== null && String(v) !== '') out[keyOf(f)] = String(v)
    }
    return out
  }, [rpc.input, values])

  // 执行：先二次确认（高危升级危险样式），确认后调执行 API（不重试），回显结果。
  const execute = async () => {
    if (!device || !submittable || running) return
    const inputs = collectInputs()
    const detail = Object.entries(inputs).map(([k, v]) => `${k} = ${v}`).join('，') || t('console.rpc.noInput')
    const ok = await confirm(
      t('console.rpc.confirmBody', { rpc: rpc.label || rpc.name, device, inputs: detail }),
      { title: t('console.rpc.confirmTitle'), danger: !!rpc.highRisk, okText: t('console.rpc.confirmOk') },
    )
    if (!ok) return // 取消 → 不下发

    setRunning(true)
    setResult('')
    try {
      const res = await executeRpc(device, module, rpc.name, inputs)
      const body: any = res.data
      if (body?.success === false) {
        setResultType('error')
        setResult(body?.message || t('console.rpc.failed'))
      } else {
        setResultType('success')
        const reply = body?.data?.reply
        setResult(
          reply && String(reply).trim()
            ? t('console.rpc.doneReply', { reply: String(reply).slice(0, 300) })
            : t('console.rpc.done'),
        )
      }
    } catch (e: any) {
      setResultType('error')
      setResult(e?.response?.data?.message || e?.message || t('console.rpc.failed'))
    } finally {
      setRunning(false)
    }
  }

  return (
    <div className="rpc-execute-tab" data-test="rpc-execute-tab">
      <div className="rpc-head">
        <span className="rpc-name">{rpc.label || rpc.name}</span>
        {rpc.highRisk && (
          <Tag color="red" data-test="rpc-highrisk">
            {t('console.rpc.highRisk')}
          </Tag>
        )}
      </div>
      <p className="rpc-tip">{t('console.rpc.tip')}</p>

      {renderFields.length === 0 ? (
        <span className="rpc-empty">{t('console.rpc.noInput')}</span>
      ) : (
        <div className="rpc-inputs">
          {renderFields.map((f) => (
            <div key={f.path} className="sub-field">
              <label className="field-label">
                {f.label}
                {f.required && <span className="req-mark">*</span>}
              </label>
              <FieldRenderer
                field={f}
                value={values[keyOf(f)]}
                onChange={(v) => setValues((prev) => ({ ...prev, [keyOf(f)]: v }))}
              />
            </div>
          ))}
        </div>
      )}

      <div className="actions">
        <Button
          type="primary"
          danger={!!rpc.highRisk}
          loading={running}
          disabled={!device || !submittable}
          onClick={() => void execute()}
          data-test="rpc-execute"
        >
          {t('console.rpc.execute')}
        </Button>
      </div>

      {result && <Alert type={resultType} showIcon message={result} data-test="rpc-result" />}
    </div>
  )
}

// frontend/src/components/config/RpcExecuteTab.vue
<template>
  <div class="rpc-execute-tab">
    <div class="rpc-head">
      <span class="rpc-name">{{ rpc.label || rpc.name }}</span>
      <el-tag v-if="rpc.highRisk" type="danger" size="small" effect="dark" data-test="rpc-highrisk">
        {{ t('console.rpc.highRisk') }}
      </el-tag>
    </div>
    <p class="rpc-tip">{{ t('console.rpc.tip') }}</p>

    <el-form label-position="top" class="rpc-form">
      <el-form-item v-for="f in resolvedInputs" :key="f.path" :label="labelOf(f)" :required="!!f.required">
        <FieldRenderer :field="f" :model-value="values[keyOf(f)]"
          @update:model-value="values[keyOf(f)] = $event" />
      </el-form-item>
      <div v-if="!resolvedInputs.length" class="rpc-empty">{{ t('console.rpc.noInput') }}</div>
    </el-form>

    <div class="actions">
      <el-button type="primary" :disabled="!device || !submittable || running"
        :loading="running" data-test="rpc-execute" @click="execute">
        {{ t('console.rpc.execute') }}
      </el-button>
    </div>

    <el-alert v-if="result" :type="resultType" :title="result" :closable="true" show-icon
      data-test="rpc-result" @close="result = ''" />
  </div>
</template>

<script setup lang="ts">
import { ref, reactive, computed, watch } from 'vue'
import { useI18n } from 'vue-i18n'
import { ElMessageBox } from 'element-plus'
import { executeRpc, getConfig } from '../../api'
import type { Field } from '../../utils/crdSchemaParser'
import type { ConsoleTab, RpcDef } from '../../utils/moduleConsole'
import { leafName } from '../../utils/moduleConsole'
import { extractRows } from '../../utils/extractRows'
import { parseLeafref } from '../../utils/leafref'
import FieldRenderer from './FieldRenderer.vue'

const props = defineProps<{
  tab: ConsoleTab
  module: string
  device: string
}>()

const { t } = useI18n()

const rpc = computed<RpcDef>(() => props.tab.rpc || { name: '', label: '', input: [] })
const values = reactive<Record<string, any>>({})
const running = ref(false)
const result = ref('')
const resultType = ref<'success' | 'error'>('success')

// leafref 输入的目标值下拉选项（键=输入叶名，FE-19）。设备/rpc 变化时按需拉取。
const leafrefOptions = reactive<Record<string, { label: string; value: string }[]>>({})

function keyOf(f: Field): string {
  return leafName(f)
}
function labelOf(f: Field): string {
  return f.label || leafName(f)
}

// 渲染用的输入字段：leafref 一律下拉（FE-19 禁自由文本）——有目标值注入 options，
// 拉取失败/为空则空下拉 + 占位提示（R08 降级=空下拉而非放开手输，mandatory 由
// submittable 自然拦截）。非 leafref 字段原样。
const resolvedInputs = computed<Field[]>(() =>
  rpc.value.input.map((f) => {
    if (!f.leafRef) return f
    const opts = leafrefOptions[keyOf(f)] ?? []
    return opts.length
      ? { ...f, options: opts }
      : { ...f, options: [], placeholder: t('console.rpc.noOptions') }
  }),
)

// 拉取每个 leafref 输入的目标列表 → 下拉选项。解析路径经 getConfig+extractRows，
// 失败静默（选项留空，渲染层兜底空下拉，不打扰执行主流程）。
async function loadLeafrefOptions() {
  for (const k of Object.keys(leafrefOptions)) delete leafrefOptions[k]
  if (!props.device) return
  for (const f of rpc.value.input) {
    const target = parseLeafref(f.leafRef)
    if (!target) continue
    try {
      const res = await getConfig(props.device, target.fetchPath)
      const rows = extractRows(res.data?.data, target.listKey, target.keyField)
      const opts = rows
        .map((r) => String(r[target.keyField] ?? ''))
        .filter((v) => v !== '')
        .map((v) => ({ label: v, value: v }))
      if (opts.length) leafrefOptions[keyOf(f)] = opts
    } catch {
      /* 拉取失败=空选项 → 空下拉（R08） */
    }
  }
}

watch(() => [props.device, rpc.value.name], loadLeafrefOptions, { immediate: true })

// 所有 mandatory input 有值才可执行（§9：校验拦截，不下发）。
const submittable = computed(() =>
  rpc.value.input.every((f) => {
    if (!f.required) return true
    const v = values[keyOf(f)]
    return v !== undefined && v !== null && String(v).trim() !== ''
  }),
)

function collectInputs(): Record<string, string> {
  const out: Record<string, string> = {}
  for (const f of rpc.value.input) {
    const v = values[keyOf(f)]
    if (v !== undefined && v !== null && String(v) !== '') out[keyOf(f)] = String(v)
  }
  return out
}

// 执行：先二次确认（高危升级警示），确认后调执行 API，回显结果/错误。
async function execute() {
  if (!props.device || !submittable.value || running.value) return

  const inputs = collectInputs()
  const detail = Object.entries(inputs).map(([k, v]) => `${k} = ${v}`).join('，') || t('console.rpc.noInput')
  const confirmMsg = t('console.rpc.confirmBody', {
    rpc: rpc.value.label || rpc.value.name,
    device: props.device,
    inputs: detail,
  })
  try {
    await ElMessageBox.confirm(confirmMsg, t('console.rpc.confirmTitle'), {
      type: rpc.value.highRisk ? 'error' : 'warning',
      confirmButtonText: t('console.rpc.confirmOk'),
      cancelButtonText: t('common.cancel'),
      confirmButtonClass: rpc.value.highRisk ? 'el-button--danger' : undefined,
    })
  } catch {
    return // 取消 → 不下发
  }

  running.value = true
  result.value = ''
  try {
    const res = await executeRpc(props.device, props.module, rpc.value.name, inputs)
    const body: any = res.data
    if (body?.success === false) {
      resultType.value = 'error'
      result.value = body?.message || t('console.rpc.failed')
    } else {
      resultType.value = 'success'
      const reply = body?.data?.reply
      result.value = reply && String(reply).trim()
        ? t('console.rpc.doneReply', { reply: String(reply).slice(0, 300) })
        : t('console.rpc.done')
    }
  } catch (e: any) {
    resultType.value = 'error'
    result.value = e?.response?.data?.message || e?.message || t('console.rpc.failed')
  } finally {
    running.value = false
  }
}
</script>

<style scoped>
.rpc-execute-tab {
  display: flex;
  flex-direction: column;
  gap: 12px;
  max-width: 560px;
}
.rpc-head {
  display: flex;
  align-items: center;
  gap: 10px;
}
.rpc-name {
  font-size: 15px;
  font-weight: 600;
  color: var(--ink-1, #1f2d3d);
}
.rpc-tip {
  font-size: 11.5px;
  color: var(--ink-3, #93a2b1);
  margin: 0;
}
.rpc-empty {
  color: var(--ink-3, #93a2b1);
  font-size: 13px;
}
.actions {
  display: flex;
  gap: 12px;
}
</style>
