// frontend/src/views/Devices.tsx
import { useCallback, useEffect, useMemo, useState } from 'react'
import { useNavigate } from 'react-router'
import { Button, Input, Modal, Select, Table, Tag, confirm, icons, toast, type TableColumnType } from '../ui'
import { i18n } from '../i18n'
import { useDeviceStore } from '../stores/device'
import { addDevice, getFleetReconcile, removeDevice } from '../api'
import { deriveDeviceRows, type DeviceRow } from '../utils/deviceRows'
import { validateDeviceForm, toAddDevicePayload, type DeviceFormInput } from '../utils/deviceForm'
import type { FleetInput } from '../composables/useFleetOverview'
import ReconcileChip from '../components/dashboard/ReconcileChip'
import Sparkline from '../components/common/Sparkline'
import './Devices.scss'

// Devices 页：设备台账（事实+会话态+对账真数据 join，离线优先）——搜索/状态/
// 厂商筛选、分页、添加（validateDeviceForm 纯函数闸门）、删除确认、探活。
// 语义自旧 Vue 版逐段平移（含「对账失败不阻断设备表」的 allSettled 边界）。
const t = (k: string, p?: Record<string, unknown>) => i18n.global.t(k, p)

const EMPTY_FORM: DeviceFormInput = { ip: '', port: '', username: '', password: '', vendor: '', role: '' }

export default function Devices() {
  const navigate = useNavigate()
  const devices = useDeviceStore((s) => s.devices)
  const fetchDevices = useDeviceStore((s) => s.fetchDevices)
  const selectDevice = useDeviceStore((s) => s.selectDevice)
  const testConnection = useDeviceStore((s) => s.testConnection)

  const [fleet, setFleet] = useState<FleetInput>({})
  const [loading, setLoading] = useState(false)
  const [searchKeyword, setSearchKeyword] = useState('')
  const [statusFilter, setStatusFilter] = useState('')
  const [vendorFilter, setVendorFilter] = useState('')
  const [page, setPage] = useState(1)
  const [pageSize, setPageSize] = useState(10)

  const load = useCallback(async () => {
    setLoading(true)
    try {
      // 设备与对账聚合并行；对账失败不阻断设备表（收敛态降级 unknown/off）。
      const [, fleetRes] = await Promise.allSettled([fetchDevices(), getFleetReconcile()])
      setFleet(fleetRes.status === 'fulfilled' ? ((fleetRes.value.data?.data as FleetInput) ?? {}) : {})
    } finally {
      setLoading(false)
    }
  }, [fetchDevices])

  useEffect(() => {
    void load()
  }, [load])

  const rows = useMemo<DeviceRow[]>(() => deriveDeviceRows(devices, fleet), [devices, fleet])
  const vendors = useMemo(() => [...new Set(rows.map((r) => r.vendor).filter(Boolean))].sort(), [rows])

  // 筛选/搜索变化回第一页，避免停在越界空页。
  useEffect(() => setPage(1), [searchKeyword, statusFilter, vendorFilter])

  const filteredRows = useMemo(() => {
    let result = rows
    if (searchKeyword) {
      const kw = searchKeyword.toLowerCase()
      result = result.filter((r) => r.ip.toLowerCase().includes(kw) || r.name.toLowerCase().includes(kw))
    }
    if (statusFilter) result = result.filter((r) => (statusFilter === 'online' ? r.online : !r.online))
    if (vendorFilter) result = result.filter((r) => r.vendor === vendorFilter)
    return result
  }, [rows, searchKeyword, statusFilter, vendorFilter])

  const goToConfig = (row: DeviceRow) => {
    // 同步写全局设备上下文（FE-10）；query 携带保证 URL 可分享（双写幂等）。
    selectDevice(row.ip)
    navigate(`/module/ifm?device=${row.ip}`)
  }

  // ── 添加设备（validateDeviceForm 纯函数为权威闸门；行内错误受控展示）──
  const [addOpen, setAddOpen] = useState(false)
  const [adding, setAdding] = useState(false)
  const [addForm, setAddForm] = useState<DeviceFormInput>(EMPTY_FORM)
  const [addErrors, setAddErrors] = useState<Partial<Record<keyof DeviceFormInput, string>>>({})

  const setF = (k: keyof DeviceFormInput, v: string) => setAddForm((prev) => ({ ...prev, [k]: v }))

  const submitAddDevice = async () => {
    const errors = validateDeviceForm(addForm)
    setAddErrors(errors)
    if (Object.keys(errors).length > 0) {
      const firstKey = Object.values(errors)[0]
      if (firstKey) toast(t(firstKey), 'error')
      return
    }
    setAdding(true)
    try {
      await addDevice(toAddDevicePayload(addForm))
      toast(t('devices.addSuccess', { ip: addForm.ip.trim() }))
      setAddOpen(false)
      await load()
    } catch (e: any) {
      // 后端拒绝（连不上/参数不合规）：不关框，展示原因供改后重试。
      toast(t('devices.addFailed', { reason: e?.response?.data?.message || e?.message || e }), 'error')
    } finally {
      setAdding(false)
    }
  }

  const handleDelete = async (row: DeviceRow) => {
    const ok = await confirm(t('devices.deleteConfirm', { ip: row.ip }), {
      title: t('common.delete'),
      danger: true,
    })
    if (!ok) return
    try {
      await removeDevice(row.ip)
      toast(t('devices.deleteSuccess', { ip: row.ip }))
      await load()
    } catch (e: any) {
      toast(t('devices.deleteFailed', { reason: e?.response?.data?.message || e?.message || e }), 'error')
    }
  }

  const handleTest = async (row: DeviceRow) => {
    const result = await testConnection(row.id)
    if (result.success) toast(t('devices.connTestSuccess', { name: row.name || row.ip }))
    else toast(`${row.name || row.ip} ${result.message}`, 'error')
  }

  const columns: TableColumnType<DeviceRow>[] = [
    {
      title: t('devices.colIp'),
      width: 150,
      render: (_, r) => <span className="mono strong">{r.ip}</span>,
    },
    { title: t('devices.colName'), width: 170, render: (_, r) => r.name },
    {
      title: t('devices.colVendorModel'),
      render: (_, r) => [r.vendor, r.model].filter(Boolean).join(' / ') || '—',
    },
    {
      title: t('devices.colRole'),
      width: 100,
      render: (_, r) => (r.role ? <Tag>{r.role}</Tag> : '—'),
    },
    {
      title: t('devices.colSession'),
      width: 120,
      render: (_, r) => (
        <Tag color={r.online ? 'green' : 'default'}>{r.online ? t('devices.online') : t('devices.offline')}</Tag>
      ),
    },
    { title: t('devices.colLoad'), width: 110, render: (_, r) => <Sparkline points={r.load} /> },
    {
      title: t('devices.colReconcile'),
      width: 120,
      render: (_, r) => <ReconcileChip state={r.reconcileState} />,
    },
    {
      title: t('devices.colLastSync'),
      render: (_, r) => <span className="mono dim">{r.lastSync || '—'}</span>,
    },
    {
      title: t('common.actions'),
      width: 200,
      fixed: 'right',
      render: (_, r) => (
        <>
          <Button type="link" size="small" onClick={() => goToConfig(r)}>
            {t('devices.viewConfig')}
          </Button>
          <Button type="link" size="small" onClick={() => void handleTest(r)}>
            {t('devices.testConnection')}
          </Button>
          <Button type="link" size="small" danger data-test="device-delete-btn" onClick={() => void handleDelete(r)}>
            {t('common.delete')}
          </Button>
        </>
      ),
    },
  ]

  const fieldError = (k: keyof DeviceFormInput) => (addErrors[k] ? t(addErrors[k]!) : undefined)

  return (
    <div className="devices" data-test="devices-page">
      <div className="page-header">
        <h1>{t('devices.title')}</h1>
        <div className="header-actions">
          <Input
            allowClear
            style={{ width: 200 }}
            placeholder={t('devices.searchPlaceholder')}
            prefix={<icons.SearchIcon />}
            value={searchKeyword}
            onChange={(e) => setSearchKeyword(e.target.value)}
          />
          <Select
            allowClear
            style={{ width: 120 }}
            placeholder={t('devices.filterStatus')}
            value={statusFilter || undefined}
            onChange={(v) => setStatusFilter(v ?? '')}
            options={[
              { label: t('devices.online'), value: 'online' },
              { label: t('devices.offline'), value: 'offline' },
            ]}
          />
          <Select
            allowClear
            style={{ width: 140 }}
            placeholder={t('devices.filterVendor')}
            value={vendorFilter || undefined}
            onChange={(v) => setVendorFilter(v ?? '')}
            options={vendors.map((v) => ({ label: v, value: v }))}
          />
          <Button icon={<icons.RefreshIcon />} onClick={() => void load()}>
            {t('common.refresh')}
          </Button>
          <Button type="primary" icon={<icons.PlusIcon />} data-test="add-device-btn" onClick={() => { setAddForm(EMPTY_FORM); setAddErrors({}); setAddOpen(true) }}>
            {t('devices.addDevice')}
          </Button>
        </div>
      </div>

      <Table
        size="small"
        rowKey="id"
        columns={columns}
        dataSource={filteredRows}
        loading={loading}
        pagination={{
          current: page,
          pageSize,
          total: filteredRows.length,
          pageSizeOptions: [10, 20, 50],
          showSizeChanger: true,
          onChange: (p, ps) => {
            setPage(ps !== pageSize ? 1 : p)
            setPageSize(ps)
          },
        }}
        locale={{ emptyText: loading ? t('devices.loadingEllipsis') : t('devices.emptyNone') }}
      />

      <Modal
        open={addOpen}
        title={t('devices.addDeviceTitle')}
        width={460}
        confirmLoading={adding}
        okText={t('common.confirm')}
        onOk={() => void submitAddDevice()}
        onCancel={() => setAddOpen(false)}
        destroyOnHidden
      >
        <div className="add-device-form" data-test="add-device-form">
          {(
            [
              ['ip', 'devices.fieldIp', true],
              ['port', 'devices.fieldPort', false],
              ['username', 'devices.fieldUsername', true],
              ['password', 'devices.fieldPassword', true],
              ['vendor', 'devices.fieldVendor', false],
              ['role', 'devices.fieldRole', false],
            ] as [keyof DeviceFormInput, string, boolean][]
          ).map(([key, labelKey, required]) => (
            <label key={key} className={`adf-item${fieldError(key) ? ' has-error' : ''}`}>
              <span className="adf-label">
                {t(labelKey)}
                {required && <i className="req">*</i>}
              </span>
              <Input
                type={key === 'password' ? 'password' : 'text'}
                value={addForm[key]}
                onChange={(e) => setF(key, e.target.value)}
                data-test={`add-${key}`}
              />
              {fieldError(key) && <span className="adf-err">{fieldError(key)}</span>}
            </label>
          ))}
        </div>
      </Modal>
    </div>
  )
}

// frontend/src/views/Devices.vue
<template>
  <div class="devices">
    <div class="page-header">
      <div>
        <h2>{{ t('devices.title') }}</h2>
        <div class="sub">{{ t('devices.subtitle') }}</div>
      </div>
      <div class="header-actions">
        <el-input v-model="searchKeyword" :placeholder="t('devices.searchPlaceholder')" :prefix-icon="Search" clearable class="search-input" />
        <el-select v-model="statusFilter" :placeholder="t('devices.allStatus')" clearable class="filter-select">
          <el-option :label="t('common.online')" value="online" />
          <el-option :label="t('common.offline')" value="offline" />
        </el-select>
        <el-select v-model="vendorFilter" :placeholder="t('devices.allVendors')" clearable class="filter-select">
          <el-option v-for="v in vendors" :key="v" :label="v" :value="v" />
        </el-select>
        <el-button :icon="Refresh" @click="handleRefresh" :loading="loading">{{ t('common.refresh') }}</el-button>
        <el-button type="primary" :icon="Plus" data-test="add-device-btn" @click="openAddDialog">{{ t('devices.addDevice') }}</el-button>
      </div>
    </div>

    <el-dialog v-model="addDialogVisible" :title="t('devices.addDeviceTitle')" width="460px">
      <div data-test="add-device-dialog">
        <el-form ref="addFormRef" :model="addForm" :rules="addRules" label-width="90px">
          <el-form-item :label="t('devices.fieldIp')" prop="ip" data-test="add-ip">
            <el-input v-model="addForm.ip" placeholder="7.225.21.14" />
          </el-form-item>
          <el-form-item :label="t('devices.fieldPort')" prop="port" data-test="add-port">
            <el-input v-model="addForm.port" placeholder="830" />
          </el-form-item>
          <el-form-item :label="t('devices.fieldUsername')" prop="username" data-test="add-username">
            <el-input v-model="addForm.username" autocomplete="off" />
          </el-form-item>
          <el-form-item :label="t('devices.fieldPassword')" prop="password" data-test="add-password">
            <el-input v-model="addForm.password" type="password" show-password autocomplete="new-password" />
          </el-form-item>
          <el-form-item :label="t('devices.fieldVendor')" prop="vendor" data-test="add-vendor">
            <el-input v-model="addForm.vendor" placeholder="huawei" />
          </el-form-item>
          <el-form-item :label="t('devices.fieldRole')" prop="role" data-test="add-role">
            <el-input v-model="addForm.role" :placeholder="t('devices.rolePlaceholder')" />
          </el-form-item>
        </el-form>
      </div>
      <template #footer>
        <el-button @click="addDialogVisible = false">{{ t('common.cancel') }}</el-button>
        <el-button type="primary" data-test="add-submit" :loading="adding" @click="submitAddDevice">
          {{ t('common.confirm') }}
        </el-button>
      </template>
    </el-dialog>

    <el-table :data="paginatedRows" class="device-table" v-loading="loading">
      <el-table-column :label="t('devices.colIp')" width="150">
        <template #default="{ row }"><span class="mono strong">{{ row.ip }}</span></template>
      </el-table-column>
      <el-table-column :label="t('devices.colName')" width="170">
        <template #default="{ row }"><span class="strong">{{ row.name || '—' }}</span></template>
      </el-table-column>
      <el-table-column :label="t('devices.colVendorModel')" min-width="150">
        <template #default="{ row }"><span class="dim">{{ row.vendorModel || '—' }}</span></template>
      </el-table-column>
      <el-table-column :label="t('devices.colRole')" width="100">
        <template #default="{ row }">
          <el-tag v-if="row.role" size="small" type="info" data-test="device-role">{{ row.role }}</el-tag>
          <span v-else class="dim">—</span>
        </template>
      </el-table-column>
      <el-table-column :label="t('devices.colSession')" width="120">
        <template #default="{ row }">
          <span class="chip" :class="row.session === 'connected' ? 'conv' : 'off'">
            <span class="glyph" aria-hidden="true"></span>{{ row.session === 'connected' ? t('devices.sessionConnected') : t('devices.sessionDisconnected') }}
          </span>
        </template>
      </el-table-column>
      <el-table-column :label="t('devices.colLoad')" width="110">
        <template #default="{ row }"><Sparkline :points="row.load" /></template>
      </el-table-column>
      <el-table-column :label="t('devices.colReconcile')" width="120">
        <template #default="{ row }"><ReconcileChip :state="row.reconcileState" /></template>
      </el-table-column>
      <el-table-column :label="t('devices.colLastSync')" min-width="140">
        <template #default="{ row }"><span class="mono dim">{{ row.lastSync || '—' }}</span></template>
      </el-table-column>
      <el-table-column :label="t('common.actions')" width="180" fixed="right">
        <template #default="{ row }">
          <el-button type="primary" size="small" link @click="goToConfig(row)">{{ t('devices.viewConfig') }}</el-button>
          <el-button type="info" size="small" link @click="handleTestConnection(row)">{{ t('devices.testConnection') }}</el-button>
          <el-button type="danger" size="small" link data-test="device-delete-btn" @click="handleDelete(row)">{{ t('common.delete') }}</el-button>
        </template>
      </el-table-column>
      <template #empty>
        <span>{{ loading ? t('devices.loadingEllipsis') : t('devices.emptyNone') }}</span>
      </template>
    </el-table>

    <div class="pagination-wrapper">
      <el-pagination v-model:current-page="currentPage" v-model:page-size="pageSize" :page-sizes="[10, 20, 50]"
        :total="filteredRows.length" layout="total, sizes, prev, pager, next, jumper"
        @size-change="handleSizeChange" @current-change="handleCurrentChange" />
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, reactive, computed, onMounted, watch } from 'vue'
import { useRouter } from 'vue-router'
import { useI18n } from 'vue-i18n'
import { Plus, Refresh, Search } from '@element-plus/icons-vue'
import { ElMessage, ElMessageBox, type FormInstance, type FormRules } from 'element-plus'
import { useDeviceStore } from '../stores/device'
import { addDevice, getFleetReconcile, removeDevice } from '../api'
import { deriveDeviceRows, type DeviceRow } from '../utils/deviceRows'
import { validateDeviceForm, toAddDevicePayload } from '../utils/deviceForm'
import type { FleetInput } from '../composables/useFleetOverview'
import ReconcileChip from '../components/dashboard/ReconcileChip.vue'
import Sparkline from '../components/common/Sparkline.vue'

const router = useRouter()
const { t } = useI18n()
const store = useDeviceStore()

const searchKeyword = ref('')
const statusFilter = ref('')
const vendorFilter = ref('')
const currentPage = ref(1)
const pageSize = ref(10)
const loading = ref(false)
const fleet = ref<FleetInput>({}) // /reconcile/status 聚合，join 出收敛态

// 设备事实 + 会话态 + 对账真数据（离线优先）。
const rows = computed<DeviceRow[]>(() => deriveDeviceRows(store.devices, fleet.value))
const vendors = computed(() => [...new Set(rows.value.map((r) => r.vendor).filter(Boolean))].sort())

// 筛选/搜索变化回到第一页，避免停在越界空页（filteredRows 有数据但 paginatedRows 空）
watch([searchKeyword, statusFilter, vendorFilter], () => {
  currentPage.value = 1
})

const filteredRows = computed(() => {
  let result = rows.value
  if (searchKeyword.value) {
    const kw = searchKeyword.value.toLowerCase()
    result = result.filter((r) => r.ip.toLowerCase().includes(kw) || r.name.toLowerCase().includes(kw))
  }
  if (statusFilter.value) result = result.filter((r) => (statusFilter.value === 'online' ? r.online : !r.online))
  if (vendorFilter.value) result = result.filter((r) => r.vendor === vendorFilter.value)
  return result
})

// 修既有缺陷：表格此前绑 filteredDevices 未真正分页，改绑 paginatedRows。
const paginatedRows = computed(() => {
  const start = (currentPage.value - 1) * pageSize.value
  return filteredRows.value.slice(start, start + pageSize.value)
})

async function load() {
  loading.value = true
  try {
    // 设备与对账聚合并行；对账失败不阻断设备表（收敛态降级为 unknown/off）
    const [, fleetRes] = await Promise.allSettled([store.fetchDevices(), getFleetReconcile()])
    fleet.value = fleetRes.status === 'fulfilled' ? (fleetRes.value.data?.data ?? {}) : {}
  } finally {
    loading.value = false
  }
}

function handleRefresh() {
  currentPage.value = 1
  load()
}

function goToConfig(row: DeviceRow) {
  // 旧配置页路由（name:'interface'）已随 FE-13 退役，跳通用模块控制台；
  // device 传 IP，与控制台设备下拉的 value 口径一致。
  // 同步写全局设备上下文（FE-10）：选一次设备，后续模块切换沿用；
  // query 仍携带以保证 URL 可分享（双写幂等）。
  store.selectDevice(row.ip)
  router.push({ name: 'module-console', params: { module: 'ifm' }, query: { device: row.ip } })
}

// ── 添加/删除设备（后端 POST/DELETE /devices 早已就绪，此处补前端入口）──

const addDialogVisible = ref(false)
const adding = ref(false)
const addFormRef = ref<FormInstance>()
const addForm = reactive({ ip: '', port: '', username: '', password: '', vendor: '', role: '' })

const ipv4Re = /^(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}$/
const addRules: FormRules = {
  ip: [
    { required: true, message: () => t('devices.ruleIpRequired'), trigger: 'blur' },
    {
      validator: (_r, v, cb) => (v && !ipv4Re.test(v) ? cb(new Error(t('devices.ruleIpInvalid'))) : cb()),
      trigger: ['blur', 'change'],
    },
  ],
  port: [
    {
      validator: (_r, v, cb) => {
        if (!v) return cb()
        const n = Number(v)
        return Number.isInteger(n) && n >= 1 && n <= 65535 ? cb() : cb(new Error(t('devices.rulePortInvalid')))
      },
      trigger: ['blur', 'change'],
    },
  ],
  username: [{ required: true, message: () => t('devices.ruleUserRequired'), trigger: 'blur' }],
  password: [{ required: true, message: () => t('devices.rulePassRequired'), trigger: 'blur' }],
  // BR-14 同口径：≤32 位 [A-Za-z0-9_-]
  role: [
    {
      validator: (_r, v, cb) => (v && !/^[A-Za-z0-9_-]{1,32}$/.test(v) ? cb(new Error(t('devices.ruleRoleInvalid'))) : cb()),
      trigger: ['blur', 'change'],
    },
  ],
}

function openAddDialog() {
  Object.assign(addForm, { ip: '', port: '', username: '', password: '', vendor: '', role: '' })
  addFormRef.value?.clearValidate()
  addDialogVisible.value = true
}

async function submitAddDevice() {
  // 闸门用纯函数（与渲染无关，见 utils/deviceForm 注释）；el-form 的 rules 只
  // 负责行内提示，故这里额外触发一次 validate() 把错误渲染出来（结果不作判据）。
  const errors = validateDeviceForm(addForm)
  addFormRef.value?.validate().catch(() => undefined)
  if (Object.keys(errors).length > 0) {
    const firstKey = Object.values(errors)[0]
    if (firstKey) ElMessage.error(t(firstKey))
    return
  }
  adding.value = true
  try {
    await addDevice(toAddDevicePayload(addForm))
    ElMessage.success(t('devices.addSuccess', { ip: addForm.ip.trim() }))
    addDialogVisible.value = false
    await load()
  } catch (e: any) {
    // 后端拒绝（连不上/参数不合规）：不关框，展示原因供改后重试
    ElMessage.error(t('devices.addFailed', { reason: e?.response?.data?.message || e?.message || e }))
  } finally {
    adding.value = false
  }
}

async function handleDelete(row: DeviceRow) {
  try {
    await ElMessageBox.confirm(t('devices.deleteConfirm', { ip: row.ip }), t('common.delete'), { type: 'warning' })
  } catch {
    return // 用户取消
  }
  try {
    await removeDevice(row.ip)
    ElMessage.success(t('devices.deleteSuccess', { ip: row.ip }))
    await load()
  } catch (e: any) {
    ElMessage.error(t('devices.deleteFailed', { reason: e?.response?.data?.message || e?.message || e }))
  }
}

async function handleTestConnection(row: DeviceRow) {
  const result = await store.testConnection(row.id)
  if (result.success) ElMessage.success(t('devices.connTestSuccess', { name: row.name || row.ip }))
  else ElMessage.error(`${row.name || row.ip} ${result.message}`)
}

function handleSizeChange(size: number) {
  pageSize.value = size
  currentPage.value = 1
}

function handleCurrentChange(page: number) {
  currentPage.value = page
}

onMounted(load)
</script>

<style scoped>
.devices {
  padding: 20px;
  display: flex;
  flex-direction: column;
  gap: 16px;
}

.page-header {
  display: flex;
  justify-content: space-between;
  align-items: flex-start;
  gap: 16px;
  flex-wrap: wrap;
}

.page-header h2 {
  margin: 0;
  font-size: 20px;
  font-weight: 600;
  color: var(--ink, #1f2d3d);
}

.page-header .sub {
  margin-top: 4px;
  font-size: 12.5px;
  color: var(--ink-3, #93a2b1);
}

.header-actions {
  display: flex;
  gap: 12px;
  flex-wrap: wrap;
  align-items: center;
}

.search-input {
  width: 240px;
}

.filter-select {
  width: 140px;
}

.device-table {
  background: var(--bg-card, #fff);
  border-radius: var(--r-card, 12px);
}

.mono {
  font-family: var(--f-mono, monospace);
}

.strong {
  font-weight: 600;
  color: var(--ink, #1f2d3d);
}

.dim {
  color: var(--ink-2, #52627a);
  font-size: 12.5px;
}

.mono.dim {
  color: var(--ink-3, #93a2b1);
  font-size: 12px;
}

/* 会话 chip（已连接/断开）——与对账 chip 同基座，配色走令牌 */
.chip {
  display: inline-flex;
  align-items: center;
  gap: 6px;
  height: 23px;
  padding: 0 9px 0 8px;
  border-radius: var(--r-chip, 999px);
  font-size: 12px;
  font-weight: 600;
  white-space: nowrap;
}

.chip .glyph {
  width: 7px;
  height: 7px;
  border-radius: 50%;
  flex-shrink: 0;
  background: currentColor;
}

.chip.conv {
  background: var(--st-conv-bg, #e4f2e8);
  color: var(--st-conv, #2f8a4c);
}

.chip.off {
  background: var(--st-off-bg, #fbe6e3);
  color: var(--st-off, #c0392b);
}

.pagination-wrapper {
  display: flex;
  justify-content: flex-end;
  padding: 8px 0;
}

@media (max-width: 768px) {
  .search-input,
  .filter-select {
    width: 100%;
    flex: 1;
    min-width: 120px;
  }
}
</style>
