// frontend/src/views/Logs.vue
<template>
  <div class="logs">
    <div class="page-header">
      <div>
        <h2>{{ t('logs.title') }}</h2>
        <div class="sub">{{ t('logs.subtitle') }}</div>
      </div>
      <div class="header-actions">
        <el-input v-model="searchKeyword" :placeholder="t('logs.searchPlaceholder')" :prefix-icon="Search" clearable class="search-input" />
        <el-select v-model="statusFilter" :placeholder="t('logs.allOutcomes')" clearable class="filter-select">
          <el-option v-for="o in statusOptions" :key="o.value" :label="o.label" :value="o.value" />
        </el-select>
        <el-button :icon="Refresh" @click="load" :loading="loading">{{ t('common.refresh') }}</el-button>
      </div>
    </div>

    <el-table :data="paginatedRows" class="logs-table" v-loading="loading">
      <el-table-column :label="t('logs.colTime')" width="180">
        <template #default="{ row }"><span class="mono dim">{{ formatTime(row.timestamp) }}</span></template>
      </el-table-column>
      <el-table-column :label="t('logs.colOp')" width="170">
        <template #default="{ row }">
          <div class="log-op">
            <div class="op-ico">
              <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 6h16M4 12h16M4 18h16" /></svg>
            </div>
            {{ row.opLabel }}
          </div>
        </template>
      </el-table-column>
      <el-table-column :label="t('logs.colDevice')" width="150">
        <template #default="{ row }"><span class="strong">{{ row.device || '—' }}</span></template>
      </el-table-column>
      <el-table-column :label="t('logs.colChange')" min-width="160">
        <template #default="{ row }"><span class="mono change">{{ row.summary || '—' }}</span></template>
      </el-table-column>
      <el-table-column :label="t('logs.colActor')" width="120">
        <template #default="{ row }"><span class="dim">{{ row.actor || '—' }}</span></template>
      </el-table-column>
      <el-table-column :label="t('logs.colOutcome')" width="130">
        <template #default="{ row }"><ReconcileChip :state="row.reconcileState" /></template>
      </el-table-column>
      <template #empty>
        <span>{{ loading ? t('logs.loadingEllipsis') : t('logs.emptyNone') }}</span>
      </template>
    </el-table>

    <div class="footnote">
      {{ t('logs.footnote') }}
    </div>

    <div class="pagination-wrapper">
      <el-pagination v-model:current-page="currentPage" v-model:page-size="pageSize" :page-sizes="[20, 50, 100]"
        :total="filteredRows.length" layout="total, sizes, prev, pager, next, jumper"
        @size-change="handleSizeChange" @current-change="handleCurrentChange" />
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, watch } from 'vue'
import { useI18n } from 'vue-i18n'
import { Refresh, Search } from '@element-plus/icons-vue'
import { getLogs } from '../api'
import { deriveLogRows, type LogRow } from '../utils/logRows'
import type { LogEntry } from '../types/api'
import { useMenuStore } from '../stores/menu'
import type { DisplayState } from '../composables/useFleetOverview'
import ReconcileChip from '../components/dashboard/ReconcileChip.vue'

const { t } = useI18n()

// FE-26：操作类型标签用模块菜单标题（name→title）；store 未加载时派生层回退段名（R08）。
const menuStore = useMenuStore()
const moduleTitles = computed(() =>
  Object.fromEntries(menuStore.nativeModules.map((m) => [m.name, m.title])),
)

const statusOptions = computed<{ label: string; value: DisplayState }[]>(() => [
  { label: t('common.state.conv'), value: 'conv' },
  { label: t('common.state.recon'), value: 'recon' },
  { label: t('common.state.drift'), value: 'drift' },
  { label: t('common.state.error'), value: 'error' },
  { label: t('common.state.unknown'), value: 'unknown' },
])

// 存原始审计记录，行派生走 computed：menu store 晚于 getLogs 返回时标签自动
// 从段名升级为菜单标题（FE-26），无需重拉。
const rawLogs = ref<LogEntry[]>([])
const rows = computed<LogRow[]>(() => deriveLogRows(rawLogs.value, moduleTitles.value))
const loading = ref(false)
const searchKeyword = ref('')
const statusFilter = ref<DisplayState | ''>('')
const currentPage = ref(1)
const pageSize = ref(20)

// 一次拉一批后客户端筛选/分页（与设备页一致）。后端 /logs 单批上限 500 条
// （maxLogLimit）；审计量超 500 时最旧记录在此不可达（低频，可接受）。
async function load() {
  loading.value = true
  try {
    const res = await getLogs({ limit: 500 })
    rawLogs.value = res.data?.data?.logs ?? []
  } catch {
    rawLogs.value = [] // 拉取失败降级空表（R08）
  } finally {
    loading.value = false
  }
}

const filteredRows = computed(() => {
  let result = rows.value
  if (searchKeyword.value) {
    const kw = searchKeyword.value.toLowerCase()
    result = result.filter((r) => r.device.toLowerCase().includes(kw) || r.actor.toLowerCase().includes(kw))
  }
  if (statusFilter.value) result = result.filter((r) => r.reconcileState === statusFilter.value)
  return result
})

const paginatedRows = computed(() => {
  const start = (currentPage.value - 1) * pageSize.value
  return filteredRows.value.slice(start, start + pageSize.value)
})

watch([searchKeyword, statusFilter], () => {
  currentPage.value = 1
})

function formatTime(iso: string): string {
  if (!iso) return '—'
  const t = new Date(iso)
  return isNaN(t.getTime()) ? iso : t.toLocaleString('zh-CN', { hour12: false })
}

function handleSizeChange(size: number) {
  pageSize.value = size
  currentPage.value = 1
}

function handleCurrentChange(page: number) {
  currentPage.value = page
}

onMounted(load)
</script>

<style scoped>
.logs {
  padding: 20px;
  display: flex;
  flex-direction: column;
  gap: 16px;
}

.page-header {
  display: flex;
  justify-content: space-between;
  align-items: flex-start;
  gap: 16px;
  flex-wrap: wrap;
}

.page-header h2 {
  margin: 0;
  font-size: 20px;
  font-weight: 600;
  color: var(--ink, #1f2d3d);
}

.page-header .sub {
  margin-top: 4px;
  font-size: 12.5px;
  color: var(--ink-3, #93a2b1);
}

.header-actions {
  display: flex;
  gap: 12px;
  flex-wrap: wrap;
  align-items: center;
}

.search-input {
  width: 240px;
}

.filter-select {
  width: 140px;
}

.logs-table {
  background: var(--bg-card, #fff);
  border-radius: var(--r-card, 12px);
}

.mono {
  font-family: var(--f-mono, monospace);
}

.strong {
  font-weight: 600;
  color: var(--ink, #1f2d3d);
}

.dim {
  color: var(--ink-2, #52627a);
  font-size: 12.5px;
}

.mono.dim {
  color: var(--ink-3, #93a2b1);
  font-size: 12px;
}

.change {
  font-size: 12.5px;
  color: var(--ink, #1f2d3d);
}

.log-op {
  display: flex;
  align-items: center;
  gap: 10px;
}

.op-ico {
  width: 30px;
  height: 30px;
  border-radius: var(--r-ctl, 8px);
  background: var(--sunken, #f4f6f9);
  display: grid;
  place-items: center;
  flex-shrink: 0;
  color: var(--ink-2, #52627a);
}

.op-ico svg {
  width: 15px;
  height: 15px;
  stroke: currentColor;
  fill: none;
  stroke-width: 1.7;
}

.footnote {
  font-size: 11.5px;
  line-height: 1.6;
  color: var(--ink-3, #93a2b1);
}

.pagination-wrapper {
  display: flex;
  justify-content: flex-end;
  padding: 8px 0;
}

@media (max-width: 768px) {
  .search-input,
  .filter-select {
    width: 100%;
    flex: 1;
    min-width: 120px;
  }
}
</style>

// frontend/src/views/Logs.tsx
import { useCallback, useEffect, useMemo, useState } from 'react'
import { Button, Input, Select, Table, icons, type TableColumnType } from '../ui'
import { i18n } from '../i18n'
import { getLogs } from '../api'
import { deriveLogRows, type LogRow } from '../utils/logRows'
import type { LogEntry } from '../types/api'
import { useMenuStore } from '../stores/menu'
import type { DisplayState } from '../composables/useFleetOverview'
import ReconcileChip from '../components/dashboard/ReconcileChip'
import './Logs.scss'

// Logs 页（FE-26）：审计台账——操作类型标签模型驱动派生（name→菜单标题，store
// 未加载回退段名 R08）；一次拉一批（≤500）后客户端筛选/分页。
const t = (k: string, p?: Record<string, unknown>) => i18n.global.t(k, p)

function formatTime(iso: string): string {
  if (!iso) return '—'
  const d = new Date(iso)
  return isNaN(d.getTime()) ? iso : d.toLocaleString('zh-CN', { hour12: false })
}

export default function Logs() {
  const nativeModules = useMenuStore((s) => s.nativeModules)
  const loadNativeModules = useMenuStore((s) => s.loadNativeModules)
  useEffect(() => {
    void loadNativeModules()
  }, [loadNativeModules])

  // FE-26：menu store 晚于 getLogs 返回时标签自动从段名升级为菜单标题，无需重拉。
  const moduleTitles = useMemo(
    () => Object.fromEntries(nativeModules.map((m) => [m.name, m.title])),
    [nativeModules],
  )

  const [rawLogs, setRawLogs] = useState<LogEntry[]>([])
  const [loading, setLoading] = useState(false)
  const [searchKeyword, setSearchKeyword] = useState('')
  const [statusFilter, setStatusFilter] = useState<DisplayState | ''>('')
  const [page, setPage] = useState(1)
  const [pageSize, setPageSize] = useState(20)

  const rows = useMemo<LogRow[]>(() => deriveLogRows(rawLogs, moduleTitles), [rawLogs, moduleTitles])

  const load = useCallback(async () => {
    setLoading(true)
    try {
      // 后端 /logs 单批上限 500（maxLogLimit）；审计量超限时最旧记录不可达（低频可接受）。
      const res = await getLogs({ limit: 500 })
      setRawLogs(res.data?.data?.logs ?? [])
    } catch {
      setRawLogs([]) // 拉取失败降级空表（R08）
    } finally {
      setLoading(false)
    }
  }, [])

  useEffect(() => {
    void load()
  }, [load])

  useEffect(() => setPage(1), [searchKeyword, statusFilter])

  const filteredRows = useMemo(() => {
    let result = rows
    if (searchKeyword) {
      const kw = searchKeyword.toLowerCase()
      result = result.filter((r) => r.device.toLowerCase().includes(kw) || r.actor.toLowerCase().includes(kw))
    }
    if (statusFilter) result = result.filter((r) => r.reconcileState === statusFilter)
    return result
  }, [rows, searchKeyword, statusFilter])

  const statusOptions: { label: string; value: DisplayState }[] = [
    { label: t('common.state.conv'), value: 'conv' },
    { label: t('common.state.recon'), value: 'recon' },
    { label: t('common.state.drift'), value: 'drift' },
    { label: t('common.state.error'), value: 'error' },
    { label: t('common.state.unknown'), value: 'unknown' },
  ]

  const columns: TableColumnType<LogRow>[] = [
    { title: t('logs.colTime'), width: 180, render: (_, r) => <span className="mono dim">{formatTime(r.timestamp)}</span> },
    {
      title: t('logs.colOp'),
      width: 170,
      render: (_, r) => (
        <span className="log-op">
          <icons.DocumentIcon className="op-ico" />
          {r.opLabel}
        </span>
      ),
    },
    { title: t('logs.colDevice'), width: 150, render: (_, r) => <span className="strong">{r.device || '—'}</span> },
    { title: t('logs.colChange'), render: (_, r) => <span className="mono change">{r.summary || '—'}</span> },
    { title: t('logs.colActor'), width: 120, render: (_, r) => <span className="dim">{r.actor || '—'}</span> },
    { title: t('logs.colOutcome'), width: 130, render: (_, r) => <ReconcileChip state={r.reconcileState} /> },
  ]

  return (
    <div className="logs" data-test="logs-page">
      <div className="page-header">
        <h1>{t('logs.title')}</h1>
        <div className="header-actions">
          <Input
            allowClear
            style={{ width: 220 }}
            placeholder={t('logs.searchPlaceholder')}
            prefix={<icons.SearchIcon />}
            value={searchKeyword}
            onChange={(e) => setSearchKeyword(e.target.value)}
          />
          <Select
            allowClear
            style={{ width: 140 }}
            placeholder={t('logs.allOutcomes')}
            value={statusFilter || undefined}
            onChange={(v) => setStatusFilter((v as DisplayState) ?? '')}
            options={statusOptions}
          />
          <Button icon={<icons.RefreshIcon />} onClick={() => void load()}>
            {t('common.refresh')}
          </Button>
        </div>
      </div>

      <Table
        size="small"
        rowKey={(r) => `${r.timestamp}-${r.device}-${r.summary}`}
        columns={columns}
        dataSource={filteredRows}
        loading={loading}
        pagination={{
          current: page,
          pageSize,
          total: filteredRows.length,
          pageSizeOptions: [20, 50, 100],
          showSizeChanger: true,
          onChange: (p, ps) => {
            setPage(ps !== pageSize ? 1 : p)
            setPageSize(ps)
          },
        }}
        locale={{ emptyText: loading ? t('logs.loadingEllipsis') : t('logs.emptyNone') }}
      />
      <div className="footnote">{t('logs.footnote')}</div>
    </div>
  )
}
