// frontend/src/views/ModuleConsolePage.tsx
import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { useParams, useSearchParams } from 'react-router'
import { Alert, Breadcrumb, Empty, Select, Tabs, Tag, Tooltip } from '../ui'
import { i18n, getLocale, subscribeLocale } from '../i18n'
import { useSyncExternalStore } from 'react'
import { getYangSchema, getOwnership } from '../api'
import { localizeFields, localizeRpcs } from '../composables/useFieldLabels'
import { useMenuStore } from '../stores/menu'
import { useDeviceStore } from '../stores/device'
import type { Field } from '../utils/crdSchemaParser'
import { deriveTabs, deriveRpcTabs, type ConsoleTab, type RpcDef } from '../utils/moduleConsole'
import ModuleListTab from '../components/config/ModuleListTab'
import ModuleFormTab from '../components/config/ModuleFormTab'
import RpcExecuteTab from '../components/config/RpcExecuteTab'
import './ModuleConsolePage.scss'

// ModuleConsolePage（FE-10/18/19/24 宿主）：通用模块控制台——schema 拉取（?device=
// 附不支持预标记 CN-05）→ 标签本地化（UI-03 懒加载原位替换，rootName 守卫防
// 竞态）→ deriveTabs 一级 Tab（rpc 不进 Tab 栏，导航落点=左树）→ 各 Tab 组件。
// rpc 直达模式仅渲染该 rpc 面板（未知名明确报错 R08）。攒批工具栏与提交编排随
// tasks 11 组在 header-actions 挂载（consoleEpoch 重挂机制已就位）。
const t = (k: string, p?: Record<string, unknown>) => i18n.global.t(k, p)

export default function ModuleConsolePage() {
  const params = useParams()
  const [searchParams] = useSearchParams()
  const moduleName = String(params.module || '')
  const rpcName = String(params.rpcName || '')
  const rpcMode = !!rpcName

  const locale = useSyncExternalStore(subscribeLocale, getLocale)
  const menuStore = useMenuStore()
  const devices = useDeviceStore((s) => s.devices)
  const selectedDeviceIp = useDeviceStore((s) => s.selectedDeviceIp)
  const selectDevice = useDeviceStore((s) => s.selectDevice)
  const fetchDevices = useDeviceStore((s) => s.fetchDevices)

  useEffect(() => {
    void fetchDevices()
  }, [fetchDevices])

  // 入页优先级 query > store：深链显式指定则覆盖全局上下文；重复参数取首个。
  useEffect(() => {
    const ip = searchParams.get('device')
    if (ip) selectDevice(ip)
  }, [searchParams, selectDevice])

  const [schemaError, setSchemaError] = useState('')
  const [title, setTitle] = useState('')
  const [vendor, setVendor] = useState('')
  const [rootName, setRootName] = useState('')
  const [schemaFields, setSchemaFields] = useState<Field[]>([])
  const [rpcs, setRpcs] = useState<RpcDef[]>([])
  const [unsupportedTabs, setUnsupportedTabs] = useState<string[]>([])
  const [activeTab, setActiveTab] = useState('')
  // 重置/提交成功 → 重挂 Tab 内容组件（tasks 11 组接线触发）。
  const [consoleEpoch] = useState(0)

  const rawRef = useRef<{ fields: Field[]; rpcs: RpcDef[] }>({ fields: [], rpcs: [] })

  const loadSchema = useCallback(async () => {
    setSchemaError('')
    setSchemaFields([])
    try {
      // 带设备取 schema：零额外请求拿到该设备的不支持预标记（CN-05）。
      const res = await getYangSchema(moduleName, 'nested', selectedDeviceIp || undefined)
      const data = res.data?.data
      setUnsupportedTabs(((data?.unsupported ?? []) as string[]) || [])
      rawRef.current = { fields: data?.fields ?? [], rpcs: (data?.rpcs ?? []) as RpcDef[] }
      setTitle(data?.title || moduleName)
      setVendor(data?.vendor || '')
      // 运行时配置路径根段 = 模块根容器名（schema title 即 root.Name()）。
      setRootName(data?.title || moduleName)
      setSchemaFields(rawRef.current.fields)
      setRpcs(rawRef.current.rpcs)
      const tabs0 = deriveTabs(data?.fields ?? [])
      setActiveTab(tabs0[0]?.name || '')
    } catch (e: any) {
      // schema 拉取失败降级：页面不崩，明确报错（R08/§9）。
      setSchemaError(e?.response?.data?.message || e?.message || t('console.schemaLoadFailed'))
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [moduleName, selectedDeviceIp])

  useEffect(() => {
    void loadSchema()
  }, [loadSchema])

  // 标签本地化（UI-03）：res 懒加载异步，首帧原始标签；rootName 守卫防快速切模块竞态。
  useEffect(() => {
    if (!rootName) return
    let alive = true
    void (async () => {
      const [lf, lr] = await Promise.all([
        localizeFields(rawRef.current.fields, rootName, locale, menuStore.leftTree),
        localizeRpcs(rawRef.current.rpcs as any, rootName, locale, menuStore.leftTree),
      ])
      if (!alive) return
      setSchemaFields(lf as Field[])
      setRpcs(lr as RpcDef[])
    })()
    return () => {
      alive = false
    }
  }, [rootName, locale, menuStore.leftTree])

  // 软归属（FE-18）：查询失败静默降级为无徽标（R08）。
  const [ownershipIntents, setOwnershipIntents] = useState<string[]>([])
  useEffect(() => {
    setOwnershipIntents([])
    if (!selectedDeviceIp || !moduleName) return
    let alive = true
    void (async () => {
      try {
        const res = await getOwnership(selectedDeviceIp)
        const claims: any[] = res.data?.data?.claims || []
        const intents = new Set<string>()
        for (const c of claims) {
          if (c?.module === moduleName && c?.intent) intents.add(c.intent)
        }
        if (alive) setOwnershipIntents([...intents].sort())
      } catch {
        /* 无徽标即可 */
      }
    })()
    return () => {
      alive = false
    }
  }, [selectedDeviceIp, moduleName])

  const tabs = useMemo<ConsoleTab[]>(() => deriveTabs(schemaFields), [schemaFields])
  const activeRpcTab = useMemo(
    () => deriveRpcTabs(rpcs).find((x) => x.rpc?.name === rpcName),
    [rpcs, rpcName],
  )
  const schemaLoaded = !!rootName
  const activeTabLabel = rpcMode
    ? activeRpcTab?.label || ''
    : tabs.find((x) => x.name === activeTab)?.label || ''

  // 运行中学习回同步（FE-24）：Tab 头淡化即时呈现。
  const onTabUnsupportedChange = useCallback((name: string, un: boolean) => {
    setUnsupportedTabs((prev) => {
      const has = prev.includes(name)
      if (un && !has) return [...prev, name]
      if (!un && has) return prev.filter((n) => n !== name)
      return prev
    })
  }, [])

  return (
    <div className="module-console" data-test="module-console">
      <div className="page-header">
        <Breadcrumb
          separator=">"
          items={[
            { title: t('console.breadcrumbConfig') },
            ...(vendor ? [{ title: vendor }] : []),
            { title },
            ...(activeTabLabel ? [{ title: activeTabLabel }] : []),
          ]}
        />
        <div className="header-actions">
          {ownershipIntents.length > 0 && (
            <Tooltip title={t('console.ownedTooltip', { intents: ownershipIntents.join('、') })}>
              <Tag color="orange" data-test="ownership-badge">
                {t('console.ownedBadge', { n: ownershipIntents.length })}
              </Tag>
            </Tooltip>
          )}
          {/* 全局设备上下文（FE-10）：选一次跨模块保持。 */}
          <Select
            style={{ width: 220 }}
            placeholder={t('console.selectDevicePlaceholder')}
            value={selectedDeviceIp || undefined}
            onChange={(v) => selectDevice(v)}
            options={devices.map((d) => ({ label: d.ip, value: d.ip }))}
            data-test="device-select"
          />
        </div>
      </div>

      {schemaError && <Alert type="error" showIcon message={schemaError} />}

      {!schemaError && !selectedDeviceIp && (
        <Empty data-test="select-device-empty" description={t('console.selectDeviceFirst')} />
      )}

      {!schemaError && selectedDeviceIp && rpcMode && (
        <>
          {activeRpcTab?.rpc ? (
            <div className="console-tabs">
              <RpcExecuteTab rpc={activeRpcTab.rpc} module={rootName} device={selectedDeviceIp} />
            </div>
          ) : schemaLoaded ? (
            <Alert
              data-test="rpc-not-found"
              type="error"
              showIcon
              message={t('console.rpcNotFound', { rpc: rpcName })}
            />
          ) : (
            <Empty description={t('console.schemaLoading')} />
          )}
        </>
      )}

      {!schemaError && selectedDeviceIp && !rpcMode && tabs.length > 0 && (
        <Tabs
          className="console-tabs"
          activeKey={activeTab}
          onChange={setActiveTab}
          items={tabs.map((tab) => ({
            key: tab.name,
            // FE-24 Tab 头淡化：设备不支持诚实透出（不隐藏），仅视觉降级。
            label: (
              <span
                className={unsupportedTabs.includes(tab.name) ? 'tab-unsupported' : undefined}
                data-test={unsupportedTabs.includes(tab.name) ? 'tab-unsupported' : undefined}
              >
                {tab.label}
              </span>
            ),
            children:
              tab.kind === 'list' ? (
                <ModuleListTab
                  key={consoleEpoch}
                  tab={tab}
                  rootName={rootName}
                  device={selectedDeviceIp}
                  unsupported={unsupportedTabs.includes(tab.name)}
                  onUnsupportedChange={(un) => onTabUnsupportedChange(tab.name, un)}
                />
              ) : (
                <ModuleFormTab
                  key={consoleEpoch}
                  tab={tab}
                  rootName={rootName}
                  device={selectedDeviceIp}
                  unsupported={unsupportedTabs.includes(tab.name)}
                  onUnsupportedChange={(un) => onTabUnsupportedChange(tab.name, un)}
                />
              ),
          }))}
        />
      )}

      {!schemaError && selectedDeviceIp && !rpcMode && tabs.length === 0 && (
        <Empty description={t('console.schemaLoading')} />
      )}
    </div>
  )
}

// frontend/src/views/ModuleConsolePage.vue
<template>
  <div class="module-console">
    <div class="page-header">
      <!-- 面包屑：配置 / 厂商 / 模块 / 激活 Tab（FE-10） -->
      <el-breadcrumb separator=">">
        <el-breadcrumb-item>{{ t('console.breadcrumbConfig') }}</el-breadcrumb-item>
        <el-breadcrumb-item v-if="vendor">{{ vendor }}</el-breadcrumb-item>
        <el-breadcrumb-item>{{ title }}</el-breadcrumb-item>
        <el-breadcrumb-item v-if="activeTabLabel">{{ activeTabLabel }}</el-breadcrumb-item>
      </el-breadcrumb>
      <div class="header-actions">
        <!-- 软归属徽标（FE-18）：本模块在选中设备上被业务意图认领时提示（不拦截）。 -->
        <el-tooltip
          v-if="ownershipIntents.length"
          :content="t('console.ownedTooltip', { intents: ownershipIntents.join('、') })"
        >
          <el-tag type="warning" size="small" data-test="ownership-badge">
            {{ t('console.ownedBadge', { n: ownershipIntents.length }) }}
          </el-tag>
        </el-tooltip>
        <!-- 全局设备上下文（FE-10）：下拉直绑 store，选一次跨模块保持。 -->
        <el-select v-model="store.selectedDeviceIp" :placeholder="t('console.selectDevicePlaceholder')" style="width: 220px">
          <el-option v-for="d in store.devices" :key="d.id" :label="d.ip" :value="d.ip" />
        </el-select>
      </div>
    </div>

    <el-alert v-if="schemaError" :title="schemaError" type="error" :closable="false" show-icon />

    <!-- 未选设备：引导先选设备（FE-10），不静默渲染空数据。
         schema 失败时让位给错误告警（此时选设备无济于事，引导反而误导）。 -->
    <el-empty
      v-if="!schemaError && !store.selectedDeviceIp"
      data-test="select-device-empty"
      :description="t('console.selectDeviceFirst')"
    />
    <!-- 一级 Tab：模块根顶层子节点派生（list→列表页、group/choice→表单页，FE-10）。
         Tab 组件常驻（不销毁），切换保留各 Tab 表单/搜索状态。 -->
    <el-tabs v-else-if="tabs.length" v-model="activeTab" class="console-tabs">
      <el-tab-pane v-for="tab in tabs" :key="tab.name" :label="tab.label" :name="tab.name">
        <ModuleListTab v-if="tab.kind === 'list'" :tab="tab" :root-name="rootName" :device="store.selectedDeviceIp" />
        <RpcExecuteTab v-else-if="tab.kind === 'rpc'" :tab="tab" :module="rootName" :device="store.selectedDeviceIp" />
        <ModuleFormTab v-else :tab="tab" :root-name="rootName" :device="store.selectedDeviceIp" />
      </el-tab-pane>
    </el-tabs>
    <el-empty v-else-if="!schemaError" :description="t('console.schemaLoading')" />
  </div>
</template>

<script setup lang="ts">
import { ref, computed, watch, onMounted } from 'vue'
import { useRoute } from 'vue-router'
import { useI18n } from 'vue-i18n'
import { getYangSchema, getOwnership } from '../api'
import { localizeFields } from '../composables/useFieldLabels'
import { useLocaleStore } from '../stores/locale'
import { useMenuStore } from '../stores/menu'
import { useDeviceStore } from '../stores/device'
import type { Field } from '../utils/crdSchemaParser'
import { deriveTabs, deriveRpcTabs, type ConsoleTab, type RpcDef } from '../utils/moduleConsole'
import ModuleListTab from '../components/config/ModuleListTab.vue'
import ModuleFormTab from '../components/config/ModuleFormTab.vue'
import RpcExecuteTab from '../components/config/RpcExecuteTab.vue'

const route = useRoute()
const localeStore = useLocaleStore()
const menuStore = useMenuStore()
const { t } = useI18n()
const store = useDeviceStore()

const moduleName = computed(() => String(route.params.module || ''))
// 入页优先级 query > store：深链/「查看配置」显式指定则覆盖全局上下文，
// 无 query 时沿用既有选中（跨模块保持）。用 watch 而非仅 setup 一次性执行：
// 组件在 /module/:module 间复用，前进/后退到携带 ?device= 的历史条目也须生效。
// 重复 query 参数取首个（数组经 String 会拼出 'a,b' 垃圾值污染全局上下文）。
function applyDeviceQuery() {
  const q = route.query?.device
  const ip = Array.isArray(q) ? q[0] : q
  if (ip) store.selectDevice(String(ip))
}
applyDeviceQuery()
watch(() => route.query?.device, applyDeviceQuery)
const schemaError = ref('')
const title = ref('')
const vendor = ref('')
const rootName = ref('')
const schemaFields = ref<Field[]>([])
// 模块 rpc（FE-19）：与容器 Tab 平级呈现；标签用后端原始名（i18n 本地化留后续）。
const rpcs = ref<RpcDef[]>([])

// 软归属（FE-18）：选中设备上本模块的认领意图清单；查询失败静默降级为无徽标（R08）。
const ownershipIntents = ref<string[]>([])
async function loadOwnership() {
  ownershipIntents.value = []
  if (!store.selectedDeviceIp || !moduleName.value) return
  try {
    const res = await getOwnership(store.selectedDeviceIp)
    const claims: any[] = res.data?.data?.claims || []
    const intents = new Set<string>()
    for (const c of claims) {
      if (c?.module === moduleName.value && c?.intent) intents.add(c.intent)
    }
    ownershipIntents.value = [...intents].sort()
  } catch {
    /* 无徽标即可，不打扰原生配置主流程 */
  }
}

// 配置容器 Tab + rpc Tab 平级合并（FE-19）：rpc 排在容器之后、同一 Tab 栏。
const tabs = computed<ConsoleTab[]>(() => [
  ...deriveTabs(schemaFields.value),
  ...deriveRpcTabs(rpcs.value),
])
const activeTab = ref('')
const activeTabLabel = computed(() => tabs.value.find((t) => t.name === activeTab.value)?.label || '')

// 原始 schema（YANG 节点名标签）；展示层按语言经 res 查表重标（UI-03）。
let rawFields: any[] = []

async function relabelFields() {
  // 查不到/缺文件回退原始标签（R08）；locale 切换即时重查。res 懒加载为异步，
  // 首帧先渲染原始标签（不阻塞 Tab 派生），就绪后原位替换。
  const root = rootName.value
  const localized = await localizeFields(rawFields, root, localeStore.locale, menuStore.leftTree)
  if (rootName.value === root) schemaFields.value = localized
}

async function loadSchema() {
  schemaError.value = ''
  schemaFields.value = []
  try {
    const res = await getYangSchema(moduleName.value, 'nested')
    const data = res.data?.data
    rawFields = data?.fields ?? []
    rpcs.value = (data?.rpcs ?? []) as RpcDef[]
    title.value = data?.title || moduleName.value
    vendor.value = data?.vendor || ''
    // 运行时配置路径的根段 = 模块根容器名（schema title 即 root.Name()）。
    rootName.value = data?.title || moduleName.value
    schemaFields.value = rawFields
    activeTab.value = tabs.value[0]?.name || ''
    void relabelFields()
  } catch (e: any) {
    // schema 拉取失败降级：页面不崩，明确报错（R08/§9）。
    schemaError.value = e?.response?.data?.message || e?.message || t('console.schemaLoadFailed')
  }
}

watch(() => localeStore.locale, relabelFields)

watch(moduleName, loadSchema)
// immediate：全局上下文使「挂载时设备已选中」成为主流程（查看配置入口/跨页返回），
// 仅靠变化触发会漏掉首帧归属查询（FE-18 徽标静默缺失）。
watch([() => store.selectedDeviceIp, moduleName], loadOwnership, { immediate: true })

onMounted(async () => {
  await Promise.allSettled([store.fetchDevices(), loadSchema()])
})
</script>

<style scoped>
.module-console {
  padding: 20px;
  display: flex;
  flex-direction: column;
  gap: 16px;
}

.page-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.console-tabs {
  background: #fff;
  border-radius: 8px;
  padding: 4px 16px 16px;
}
</style>
